### ISSUE TITLE
Trouble interacting factor variables with many unique values in MTRs

### ISSUE THREAD

**Issue by johnnybonney** [jkcshea/ivmte#156]
When a factor variable takes on many values (i.e. more than 20) and that variable is interacted with the `u`-portion, things break.

See the example below. Some notes:
- When `x` takes on 21+ values, the function breaks (otherwise it works)
- When the `u`-portion is a spline, things work correctly, so this seems to be a problem with linear/polynomial `u` specifications

```
library(data.table)
library(ivmte)

set.seed(1001)
N <- 10000

dt <- data.table(
  id = 1:N,
  u = runif(N),
  z = sample(1:4, N, replace = T),
  x = sample(1:21, N, replace = T), # 20 works, 21 doesn't
  epsilon = rnorm(N, sd = .1)
)

dt[, p := (z == 1)*0.12 + (z == 2)*0.29 + (z == 3)*0.48 + (z == 4)*0.78]
dt[, d := as.integer(u <= p)]
dt[, y0 := 0.9 - 1.1*u + 0.3*u^2]
dt[, y1 := 0.35 - 0.3*u - 0.05*u^2]
dt[, y := y1*d + y0*(1 - d) + epsilon]

args_test <- list(
  data = dt,
  propensity = d ~ factor(x) + factor(z),
  ivlike = c(y ~ d + factor(x),
             y ~ factor(z) + factor(x)),
  components = l(c(d), c(factor(z))),
  # in m0 and m1, replace u with a uSpline and things work
  m0 = ~factor(x) + factor(x):u, 
  m1 = ~factor(x) + factor(x):u,
  target = "ate",
  lpsolver = "gurobi"
)

test_res <- do.call(ivmte, args_test)
```
```
LP solver: Gurobi ('gurobi')

Obtaining propensity scores...

Generating target moments...
    Integrating terms for control group...
    Integrating terms for treated group...

Generating IV-like moments...
    Moment 1...
    Moment 2...
    Moment 3...
    Moment 4...
    Independent moments: 4 

Performing audit procedure...
    Generating audit grid...
    Generating initial constraint grid...
 Error in `[<-`(`*tmp*`, , i, value = 0) : subscript out of bounds 
```

**Comment by jkcshea** [comment]
Done!

The problem stemmed from here:
https://github.com/jkcshea/ivmte/blob/db6eee0d13f305871daa0d26f5acd9b155111ae0/R/monobound.R#L786-L798
Previously, the lines `A0 <- as.data.frame(A0)` and `A1 <- as.data.frame(A1)` were not there.
However, I was assigning new columns as if the objects `A0` and `A1` were `data.frames`.
While this was indeed the case for `uSplines`, it was not for regular polynomial `u`s---the `A0` and `A1` objects were just matrices.

So the issue was resolved simply by converting `A0` and `A1` to polynomials.
