### ISSUE TITLE
Setting LP-solver options causes audit to iterate when it shouldn't

### ISSUE THREAD

**Issue by johnnybonney** [jkcshea/ivmte#164]
If I set the audit grid and the initial grid to be equal, the audit procedure should never perform more than one iteration. However, specifying `lpsolver.options` causes the audit to iterate multiple times.

Specifically, I am seeing the following output.
Without `lpsolver.options` specified:
```
Performing audit procedure...
    Generating audit grid...
    Generating initial constraint grid...

    Audit count: 1
    Minimum criterion: 0.2798145
    Obtaining bounds...
    Violations: 0
    Audit finished.

Bounds on the target parameter: [0.0187602, 0.03944839]
```
Same exact arguments but now with `lpsolver.options.bounds = list(presolve = 0)`:
```
Performing audit procedure...
    Generating audit grid...
    Generating initial constraint grid...

    Audit count: 1
    Minimum criterion: 0.2798145
    Obtaining bounds...
    Violations:  8640 
    Expanding constraint grid to include 2602 additional points...

    Audit count: 2
    Minimum criterion: 0.2798145
    Obtaining bounds...
```
In both cases, `initgrid.nx = audit.nx = 1816` and `initgrid.nu = audit.nu = 50`. What is happening here? I wouldn't think that `lpsolver.options` should impact the number of audit iterations whatsoever.

[Here is a zip-file](https://github.com/jkcshea/ivmte/files/4036948/grid_trouble.zip) that contains code and data to reproduce the error.

**Comment by a-torgovitsky** [comment]
It's certainly possible that it changes the number of audits, since solutions to linear programs are generally not unique (only the optimal value is), so the MTR functions at the optimum could be different if the algorithm is different.

However, the bounds at the end of the audit procedure should be the same (or very similar).
Is that true in this situation?

**Comment by johnnybonney** [comment]
I agree that it can change the number of audits **if** the initial grid isn't set to equal the audit grid. The key here is that I did set the initial grid equal to the audit grid.

From my understanding, violations should not be possible in this case (and it shouldn't be possible for more points to be added from the audit grid, either). So when it says I have 8640 violations -- I don't know how, since every single point in the audit grid should have been explicitly constrained in the initial optimization problem, and thus all the constraints should be satisfied.

> However, the bounds at the end of the audit procedure should be the same (or very similar).
Is that true in this situation?

I didn't check that (I cut the program off, since each audit iteration took so long), but I will.

**Comment by a-torgovitsky** [comment]
I see, missed that part.
I agree that it looks strange.

**Comment by jkcshea** [comment]
Hm, this is indeed very strange.
R is verifying that the audit grid and the initial grid are identical.
However, violations are still being found...

When the user passes options, there is a feasibility tolerance in Gurobi that can be set.
Recall from before that a discrepancy between Gurobi's feasibility tolerance, and our tolerance when checking for violations, resulted in a similar issue.
However, I had written code to account for this already.

I will continue to investigate...

**Comment by jkcshea** [comment]
I've been playing with this on Gurobi 8 and 9, and it looks like a scaling issue.

To be clear:
@johnnybonney's problem arises because Gurobi thinks it has solved the LP problem, satisfying all the constraints.
Since the constraints in the LP problem include the entire audit grid, the solution should satisfy the audit.
However, our code for checking violations indicates this is not the case.
So there is clearly some discrepancy in what Gurobi thinks is feasible, and what R thinks is feasible.

As mentioned above, it is not because of a discrepancy in the tolerances used to check feasibility.
Unless the user specifies the `FeasibilityTol` option for Gurobi, the `ivmte` function will set `FeasibilityTol = 1e06` by default---this is indeed happening. 
This is the same tolerance `ivmte` uses when checking for violations.

In Gurobi 8 and 9, when @johnnybonney's issue pops up, the solutions to the LP problem involves enormous MTR coefficients like `-1.833772e+12` and `1.833772e+12`.
I thought a possibility was that these massive coefficients are multiplying tiny numbers that Gurobi treats as 0s (anything less than `1e-13` is treated as 0 by Gurobi), but R does not, leading to the discrepancy @johnnybonney uncovered.
However, the problematic constraints do not involve tiny numbers!
Rather, things that get multiplied by `-1.833772e+12` and `1.833772e+12` end up summing to something reasonable.
e.g.
```R
> ## Enormous MTR coefficients
> res$gstar.coef$max.g0[c(4, 42:48)]
       factor(dccode0)24 u0S1.1:factor(dccode0)24 u0S1.2:factor(dccode0)24 
           -1.833784e+12             1.833784e+12             1.833784e+12 
u0S1.3:factor(dccode0)24 u0S1.4:factor(dccode0)24 u0S1.5:factor(dccode0)24 
            1.833784e+12             1.833784e+12             1.833784e+12 
u0S1.6:factor(dccode0)24 u0S1.7:factor(dccode0)24 
            1.833784e+12             1.833784e+12 
> ## Corresponding entries in the constraint matrix
> badRows[1, ][c(4, 42:48)]
       factor(dccode0)24 u0S1.1:factor(dccode0)24 u0S1.2:factor(dccode0)24 
             1.000000000              0.324951172              0.551452637 
u0S1.3:factor(dccode0)24 u0S1.4:factor(dccode0)24 u0S1.5:factor(dccode0)24 
             0.118509928              0.005086263              0.000000000 
u0S1.6:factor(dccode0)24 u0S1.7:factor(dccode0)24 
             0.000000000              0.000000000 
> ## Their inner product
> sum(res$gstar.coef$max.g0[c(4, 42:48)] * badRows[1, ][c(4, 42:48)])
[1] -0.8926182
```

I think the problem is that Gurobi's output is not precise enough.
That is, `-1.833772e+12` and `1.833772e+12` is not precise enough for us to replicate Gurobi's feasibility check. 
After all, Gurobi switches to quad precision when solving these problems.
As a result, `ivmte` suffers from rounding errors when checking for violations.
And in this case, it (seems to have) led to this issue.

Some reactions:
1. It does not seem possible to have Gurobi return output with quad precision.
I can post a question about this.
1. I can update the code so that it knows not to repeat audits whenever the audit grid and initial grid are the same size.
However, I do think keeping the check for violations is useful.
After all, this example informed us that something was wrong with the LP problem.
If the above makes sense, I can include a warning to the user about scaling issues whenever a problem like this arises.

**Comment by a-torgovitsky** [comment]
When you say this

> That is, -1.833772e+12 and 1.833772e+12 is not precise enough for us to replicate Gurobi's feasibility check.

Do you mean Gurobi only returns 7 significant digits?

**Comment by jkcshea** [comment]
Using the `format(..., scientific = FALSE)` command, I saw that It does return 12 digits, but no decimal places.
The constraints are only being violated by a small amount (e.g. magnitudes of `1e-4` and `1e-5`), so I was thinking it was the loss of decimals that's causing this.

**Comment by a-torgovitsky** [comment]
Are you looking at absolute magnitudes? Maybe there is a way to convert to relative magnitudes?

**Comment by jkcshea** [comment]
Sorry, I realized I misunderstood what you meant by your question.

Yes, I am indeed using absolute tolerance to check for violations of the shape constraint.
I could switch to relative tolerance when checking violations, but I believe this problem should still persist.

For instance, in the example above, the default constraint `m0.lb = -0.4963692` is being violated.
At one point of the audit grid, we have `m0 = -0.4963818`.
The absolute violation is `1.257658e-05`.
The relative violation is `2.533715e-05`.
(I'm using the formula `abs(x - y) / min(abs(x), abs(y))`.)

I could use something other than `m0.lb` as the baseline when calculating the relative violation.
But using `m0.lb` seems like the most reasonable thing to do.

----------------
A few extra things I noticed about the violations:
1. Many of violations were of the same magnitude.
So I suspect several of the constraints were supposed to be binding.
1. Not all the violations involve the enormous coefficients.
But some of the covariates get reasonably large (up to 200).
So I suspect the loss of quad precision can also explains these cases.

**Comment by a-torgovitsky** [comment]
Hmm. Just a wild guess here, but what happens if you round the lower bound to a nicer number? Say -.5? Does that change things?

**Comment by jkcshea** [comment]
It does, actually.
The problem above still occurs (i.e. MTR coefficients with magnitude `1e+12`, and violations in the audit).
However, the number of violations has reduced from 532 to 227.

**Comment by a-torgovitsky** [comment]
Suppose we make our audit tolerance slightly more forgiving than the tolerance used in Gurobi.
Then we wouldn't have this problem, right?
(And the similar issue we ran into before was because our tolerance was _less_ forgiving than Gurobi's, right?)

Is that going to cause some unforeseen problems elsewhere?
It would mean we potentially get a solution that violates some of the shape constraints by negligible amounts.
That doesn't seem like a big issue.
But maybe I am forgetting something.

**Comment by jkcshea** [comment]
>Suppose we make our audit tolerance slightly more forgiving than the tolerance used in Gurobi.
Then we wouldn't have this problem, right?
(And the similar issue we ran into before was because our tolerance was less forgiving than Gurobi's, right?)

Yes and yes.
I also don't foresee problems other than minor violations of the shape constraints and wider bounds.

The largest violation in this example is `0.000199765 > 1e-04`.
Do we want to be as forgiving as setting the tolerance at `1e-3`?
Or maybe set it as `5e-4`?

In the case of Gurobi, it is possible that we only increasing our tolerance _conditional_ on Gurobi using quad precision.
This will require us to generate a log file, as that is the only indication that quad precision is used.
The log file shouldn't take much memory, though, and can be removed after checking the precision.
Let me know if you'd like me to do this, or if it's too much.

I'll also try the example above on CPLEX and lp_solve (but the latter I doubt will handle this problem well).

**Comment by a-torgovitsky** [comment]
The log file seems excessive.
But is there a way to adjust our tolerance based on Gurobi's?
A hard choice such as 1e-3 is bound to cause problems.

**Comment by jkcshea** [comment]
Oh sure.
Gurobi's tolerance is either set by us to its default level of `1e-06`, or it is set by the user.
So we always know Gurobi's tolerance, and can adjust our tolerance accordingly.

Gurobi's tolerance can range from `1e-2` to `1e-9`.
Is there a clear way to map Gurobi's tolerance to a new set of tolerances?

**Comment by a-torgovitsky** [comment]
What values would solve the problem in the above example?

I think we want to make this an option, then by default set it to the smallest value such that we don't have a problem in this example.
That way the user can override it if necessary.

**Comment by jkcshea** [comment]
I take it you mean, "What tolerance value in our audit will solve the above example?"
The smallest (with 1 significant figure) would be `2e-04` (the largest violation is `0.000199765`).
(But in case you were referring to Gurobi's tolerance: changing Gurobi's tolerance couldn't resolve the issue.)

But do we want to let this somewhat extreme example determine the default tolerance for the audit?
This is the first time we've ever seen Gurobi's feasibility check differ from our audit.

It's very easy to detect whenever this issue pops up.
So should we consider having the audit's tolerance and Gurobi's tolerance continue to be `1e-06` by default, but automatically adjust the audit's tolerance to `2e-04` whenever this issue pops up?
And of course, there will be a warning thrown out, and the user will have an option of overriding the default adjustment to `2e-04`.

**Comment by a-torgovitsky** [comment]
I think that sounds good, but let's make it always half of Gurobi's tolerance, so that in this case it is `1e-03`.

**Comment by jkcshea** [comment]
Done!

Here's what the output for the example above looks like now:

```R
    Moment 37...
    Moment 38...
    Independent moments: 38 

Performing audit procedure...
    Generating audit grid...
    Generating initial constraint grid...

    Audit count: 1
    Minimum criterion: 0.2798145
    Obtaining bounds...
    Violations: 0
    Audit finished.

Warning: 1023 violations originally found despite 
the LP constraint grid and audit grid being identical. 
Audit tolerance was increased from 1e-06 to 1e-03. 
This suggests precision of the LP solver exceeds that 
of R, and may be due to scaling issues in the LP model.

Bounds on the target parameter: [0.01893964, 0.4302528]

```
From now on, the audit should always terminate whenever the initial grid and audit grid are of the same size.

Here's the output when the problem still persists.
I achieved this by setting our audit's tolerance to be very small, `audit.tol = 1e-10`.
```R
    Moment 37...
    Moment 38...
    Independent moments: 38 

Performing audit procedure...
    Generating audit grid...
    Generating initial constraint grid...

    Audit count: 1
    Minimum criterion: 0.2798145
    Obtaining bounds...
    Violations:  1023 
Warning: Audit finished: violations continue to occur 
although the LP constraint grid and audit grid are 
identical, and the audit tolerance has increased from 
1e-10 to 1e-05. This suggests precision of the LP solver 
exceeds that of R, and may be due to scaling issues in 
the LP model. Setting 'audit.tol' to be larger than the 
maximum violation of 1.99765e-04 will eliminate this 
message, but will not address the nature of the problem.

Bounds on the target parameter: [0.01893964, 0.4302528]
```
In the event that this problem arises when the user sets `audit.tol` to something like `audit.tol = 2.34e-07` (the magnitude is odd), then `ivmte` will be generous and adjust `audit.tol` to `2.34e-03` rather than `2.34e-04`.


Let me know if you want any thing changed.

**Comment by a-torgovitsky** [comment]
That looks great!

But what's the purpose of this last bit?

> In the event that this problem arises when the user sets audit.tol to something like audit.tol = 2.34e-07 (the magnitude is odd), then ivmte will be generous and adjust audit.tol to 2.34e-03 rather than 2.34e-04.

**Comment by jkcshea** [comment]
Oh, that last part was because we said earlier to use "half" of Gurobi's tolerance in these situations, i.e. half the exponent in the scientific notation.
So in that example, I decided to let `2.34e-03` be "half" of `2.34e-07` instead of `2.34e-04`.
I could use `2.34 * 10^(-3.5)` if you prefer.

**Comment by a-torgovitsky** [comment]
Yeah, let's just use straight half so there's no ambiguity.
The `2.34e-07` comes from Gurobi?
Or this is a hypothetical tolerance that a (strange) user could potentially pass to Gurobi?

**Comment by jkcshea** [comment]
Sure, I'll switch to actually using half the magnitude.
The `2.34e-07` was indeed a hypothetical tolerance. I thought it would look nice if we were just scaling the tolerances by 10.
