### ISSUE TITLE
Unbounded LP problem when grid should be sufficient

### ISSUE THREAD

**Issue by johnnybonney** [jkcshea/ivmte#169]
[Here are data and code](https://github.com/jkcshea/ivmte/files/4294003/gelbach_ex.zip) that generate the behavior I was describing [here](https://github.com/jkcshea/ivmte/issues/166#issuecomment-595303021).

To summarize the example:
- there are 10,932 observations in the data (each with a unique combination of the 11 covariates). 
- the MTRs are roughly specified as ` ~x1:uSplines(deg = 0, knots = u_knots) + ... + x11:uSplines(deg = 0, knots = u_knots)`
  - `u_knots` is 8 knots based on the distribution of the propensity score, which turns out to be approximately `c(0.09, 0.33, 0.48, 0.65, 0.75, 0.81, 0.87, 0.98)`.

Given these MTRs, I would expect `initgrid.nu = 200` and `intigrid.nx = 10932` to be sufficient to constrain any u in [0, 1] and any x in the empirical support of X. Yet, the LP problems are unbounded.

**Comment by jkcshea** [comment]
I finally found the problem.
Turns out it was a programming error I made a long time ago, where I used `grepl` instead of `==` early on in the process of constructing the constraint matrices.
I just pushed the changes, let me know if this problem is still popping up.

**Comment by johnnybonney** [comment]
Great. I will take a look. Should I be worried about the accuracy of past results, or is this just an error that would prevent LP problems from being solvable?

**Comment by jkcshea** [comment]
> Should I be worried about the accuracy of past results, or is this just an error that would prevent LP problems from being solvable?

Argh, yes, somehow I didn't think about that.
I believe the error is a sufficient condition for the LP problem to be unbounded, but I would still check certain specifications.

What the mistake effectively did was zero-out columns in the constraint matrix for certain interactions between `x` and a spline.
Specifically, it occurs whenever the name of the `x` variable is a strict subset of another, e.g. `age`, `age2`, `age3`. (*)
The implication for the LP problem is that these interaction terms do not enter into the shape constraints. 
As a result, the LP problem becomes unbounded, since those variables are free to blow up (I'm assuming you're underidentified to begin with).

I think this is a sufficient condition for the LP problem to be unbounded, i.e. if you're getting bounds, then you're not affected by this problem.
Nevertheless, I would check the results from specifications satisfying the (*) description above.
This will most likely be those where you created your own polynomials (e.g.`age`, `age2`, `age3`).

I'm terribly sorry about this.

**Comment by johnnybonney** [comment]
Good to know. Most of our specifications don't use those polynomials, so it is probably unlikely that we had any problems, but we will be sure to re-run things in the near future just in case.

And I can confirm that the recent updates fixed the issue I posted -- I am now getting bounds.

**Comment by jkcshea** [comment]
> Most of our specifications don't use those polynomials, so it is probably unlikely that we had any problems

Ah, that's a relief.
Thanks for taking this news so nicely.

> but we will be sure to re-run things in the near future just in case.

That would be good, hopefully the results are as before.
But if not, I suppose that means we'll catch another error.

> And I can confirm that the recent updates fixed the issue I posted -- I am now getting bounds.

Excellent, then I'll close this issue.
