### ISSUE TITLE
Do we run in parallel when bootstrapping?

### ISSUE THREAD

**Issue by a-torgovitsky** [jkcshea/ivmte#181]
Just wondering if that was something that was ever implemented.
Should be "embarrassingly parallel" right?

**Comment by jkcshea** [comment]
Hm, I did not implement this. 
But yes, it should indeed be straightforward to implement.

Some reasonable options to add are:
1. Whether or not to parallelize (e.g. if the user is on a server, then they may have to manually code up the parallelization to adhere to server rules).
I'm thinking of no parallelization by default.
1. Which R library to use for parallelization.
I believe different packages have different syntax.
Hopefully this won't be too difficult to set up---it should simply be different ways of setting up loops.
1. Number of processors to use.

Anything else you think we should add?

**Comment by a-torgovitsky** [comment]
The future package takes care of 1 and 3 I think in the sense that it
leaves it up to the user to declare how many cores they want to use or
whether they want to distribute etc.

Then all that changes in our code is some parts are declared to be things
that should run according to the user's preferences.

That's my understanding of how it works anyway.

**Comment by jkcshea** [comment]
Okay, I'll read up on the `future` package and let you know if any complications arise.

**Comment by jkcshea** [comment]
Sorry to take a while to get to this.

[example.zip](https://github.com/jkcshea/ivmte/files/5270298/example.zip)
In the attached example, I have a toy setup for `ivmte` to work with the `future` package.
There appears to be a large overhead cost, since bootstrapping via `future` takes about 5 times as long as using just one processor.

Why exactly this is the case is unclear to me, but I think it has to do with how `future` prepares the calls for multiple processors.
For instance, this line in the example:
```R
plan(list(tweak(multisession, workers = 2L),
          tweak(multisession, workers = 4L)))
```
means "Allow 2 tasks to be run simultaneously, and each of those tasks can call on 4 processors."
So when running the script, the future for `ivmte` is treated as the second task, and is executed on 4 processors.
The first task is still the main script, which will keep running, unless the value of the future is needed but is not yet available.
In this setting, using futures takes about 5 times longer.

Under the setting below, it also takes about 5 times longer (`ivmte` is still being executed on 4 processors).
```R
plan(list(tweak(multisession, workers = 5L),
          tweak(multisession, workers = 1L)))
```
The same as with the next setting.
```R
plan(list(tweak(multisession, workers = 1L),
          tweak(multisession, workers = 4L)))
```
But this single-core setting takes only twice as long.
```R
plan(list(tweak(multisession, workers = 1L),
          tweak(multisession, workers = 1L)))
```

I can incorporate the `future` package into `ivmte`, though.
Maybe it's useful for the user to be able to continue interacting with R while the bootstrap is being run in the background.

I will check how the performance is for some other parallelization packages that may be used on servers, i.e. the ones that use the `%dopar%` syntax.

**Comment by a-torgovitsky** [comment]
Hmm, your implementation of future is quite a bit different than the way I've used it before.
I usually use it something like this: https://www.jottr.org/2018/06/23/future.apply_1.0.0/ with `future_lapply`.
For Monte Carlos (basically the same as bootstrap) I usually see appropriate parallelization gains.
Seems much easier than the way you have implemented it?
It also avoids the need to mess around with the seed, which we want to avoid.

Then I would expect the user could do something like this before calling `ivmte`:
```r
plan(multicore, workers = 4)
```
and the bootstrapping would be parallelized

**Comment by jkcshea** [comment]
Ah, I see.
I was looking at the `future` package, and was following its vignette.
This `future.apply` package looks very nice, I think it should work nicely.

**Comment by a-torgovitsky** [comment]
My (limited) understanding is that `future` is both the heavy-duty back-end, for use mainly by people doing complicated stuff, as well as the front-end for the user.
For our purposes we have an embarrassingly parallel problem, so I think `future.apply` will work well.
Then the user would do something like
```r
library("future")
plan(multicore, workers = 4)
ivmte(...) # everything inside here with future_lapply gets run in parallel with 4 workers
```

**Comment by jkcshea** [comment]
Done!
Attached is a simple demonstration for the bounds (bootstrapping for point estimates have also been parallelized).
Using sequential bootstraps, the total run time is about 40 seconds.
Using `future.apply` and 4 cores, this is cut to about about 15 seconds.
[fix-issue181.zip](https://github.com/jkcshea/ivmte/files/5285905/fix-issue181.zip)

The estimates using the original sample are not performed in parallel with the bootstraps.
The reason is that we need the estimates from the original sample in order to re-center the test statistics for the specification tests.

The package will detect whether or not the user loaded `future` or `future.apply` into the R session.
If so, bootstraps are automatically done using futures.

**Comment by a-torgovitsky** [comment]
Nice, that sounds about right regarding time.

What do you mean by this?
> The package will detect whether or not the user loaded future or future.apply into the R session.
If so, bootstraps are automatically done using futures.

Isn't this automatic already?
What do you mean by
> bootstraps are automatically done using futures.

**Comment by jkcshea** [comment]
Ah, sorry that was unclear.

As in your example and the link you posted, `future` is only used when a `future_FUN()` function is used.
If the user doesn't have the `future` package installed, or they didn't load the library to declare something like `plan(multicore, ...)`, then I presume they don't want to do things in parallel.
Thus, `ivmte` will bootstrap sequentially.

If the user does have the `future` and `future.apply` packages installed, and they have those libraries loaded in their R session, then I presume that means they want do things in parallel.
Thus, `ivmte` will use `future_lapply` to perform the bootstrap.

**Comment by jkcshea** [comment]
If that setup sounds reasonable to you, I can also incorporate this into the vignette.
It will certainly help with compiling the vignette (it takes quite a while at the moment).
And then we can update the version on CRAN.

**Comment by a-torgovitsky** [comment]
Brilliant, sounds good.

I think you put in more effort than people usually would.
Typically I think you'd just make `future.apply` a dependency, then leave it up to the user to install `future` and invoke it before calling `ivmte`. But since you already put in the work to do the checks, that's great! Nice!
