### ISSUE TITLE
Bug when specifying intercept = FALSE in spline

### ISSUE THREAD

**Issue by a-torgovitsky** [jkcshea/ivmte#192]
[data_example.csv.zip](https://github.com/jkcshea/ivmte/files/5247036/data_example.csv.zip)

This works
```r
library(ivmte)

data <- fread("data_example.csv")

args <- list(data = data,
             target = "ate",
             ivlike = YD ~ Z1,
             propensity = D ~ Z1,
             m1 = ~ uSplines(degree = 0, knots = c(.5, .75), intercept = FALSE),
             m0 = ~ 1,
             m0.lb = 0,
             m0.ub = 0)
do.call(ivmte, args)
```
but if I only have a single knot, I get an error
```r
args[["m1"]] <- ~ uSplines(degree = 0, knots = c(.5), intercept = FALSE)
do.call(ivmte, args)
```
yields
```r
Error in colMeans(splinesGamma) : 
  'x' must be an array of at least two dimensions
```

**Comment by jkcshea** [comment]
This was happening because R likes to convert matrices with one row or one column into a vector.
In the second specification, since there is only one knot and no intercept, the spline component consists of just 1 variable.
That means a matrix with only one column, and at some point R converts that into a vector.
This has now been corrected.

**Comment by a-torgovitsky** [comment]
Thanks

> This was happening because R likes to convert matrices with one row or one column into a vector.

I've certainly run into this before. It's a bit annoying.
